version: '3.9'

services:
  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - popcorn-network
    volumes:
      - rdb:/data
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
  # Popcorn
  popcorn:
    build:
      context: .
      dockerfile: Dockerfile
    image: popcorn:latest
    container_name: popcorn
    ports:
      - "8080:8080"
    env_file:
      - config/secrets.env
      - config/prod.env
    depends_on:
      - redis
    networks:
      - popcorn-network
    command: server

volumes:
  rdb:
    driver: local
networks:
  popcorn-network:
    name: popcorn-network
    external: true