version: '3.9'

services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d/:ro
    networks:
      - popcorn-network

networks:
  popcorn-network:
    name: popcorn-network
    external: true